// <auto-generated />
namespace ITintheDWebsite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDBEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDBEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "201307291942308_AddDBEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
